//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR.Integracao.ServicoColaborador {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Retorno", Namespace="http://ws.cassi.com.br/v1/retornos/Retorno")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GIR.Integracao.ServicoColaborador.RetornoListaColaborador))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GIR.Integracao.ServicoColaborador.RetornoColaborador))]
    public partial class Retorno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoListaColaborador", Namespace="http://ws.cassi.com.br/v1/retornos/RetornoListaColaborador")]
    [System.SerializableAttribute()]
    public partial class RetornoListaColaborador : GIR.Integracao.ServicoColaborador.Retorno {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoColaborador.Colaborador[] ColaboradoresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoColaborador.Colaborador[] Colaboradores {
            get {
                return this.ColaboradoresField;
            }
            set {
                if ((object.ReferenceEquals(this.ColaboradoresField, value) != true)) {
                    this.ColaboradoresField = value;
                    this.RaisePropertyChanged("Colaboradores");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoColaborador", Namespace="http://ws.cassi.com.br/v1/retornos/RetornoColaborador")]
    [System.SerializableAttribute()]
    public partial class RetornoColaborador : GIR.Integracao.ServicoColaborador.Retorno {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoColaborador.Colaborador ColaboradorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoColaborador.Colaborador Colaborador {
            get {
                return this.ColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColaboradorField, value) != true)) {
                    this.ColaboradorField = value;
                    this.RaisePropertyChanged("Colaborador");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Colaborador", Namespace="http://ws.cassi.com.br/v2/modelos/Colaborador")]
    [System.SerializableAttribute()]
    public partial class Colaborador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string LoginColaboradorField;
        
        private string NomeCompletoColaboradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeResumidoColaboradorField;
        
        private string EmailColaboradorField;
        
        private string MatriculaColaboradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeCargoColaboradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTelefoneColaboradorField;
        
        private GIR.Integracao.ServicoColaborador.UnidadeOrganizacional UnidadeOrganizacionalColaboradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeGerenteColaboradorField;
        
        private string CPFColaboradorField;
        
        private bool IsAtivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LoginColaborador {
            get {
                return this.LoginColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginColaboradorField, value) != true)) {
                    this.LoginColaboradorField = value;
                    this.RaisePropertyChanged("LoginColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NomeCompletoColaborador {
            get {
                return this.NomeCompletoColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeCompletoColaboradorField, value) != true)) {
                    this.NomeCompletoColaboradorField = value;
                    this.RaisePropertyChanged("NomeCompletoColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeResumidoColaborador {
            get {
                return this.NomeResumidoColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeResumidoColaboradorField, value) != true)) {
                    this.NomeResumidoColaboradorField = value;
                    this.RaisePropertyChanged("NomeResumidoColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string EmailColaborador {
            get {
                return this.EmailColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailColaboradorField, value) != true)) {
                    this.EmailColaboradorField = value;
                    this.RaisePropertyChanged("EmailColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string MatriculaColaborador {
            get {
                return this.MatriculaColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaColaboradorField, value) != true)) {
                    this.MatriculaColaboradorField = value;
                    this.RaisePropertyChanged("MatriculaColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string NomeCargoColaborador {
            get {
                return this.NomeCargoColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeCargoColaboradorField, value) != true)) {
                    this.NomeCargoColaboradorField = value;
                    this.RaisePropertyChanged("NomeCargoColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string NumeroTelefoneColaborador {
            get {
                return this.NumeroTelefoneColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTelefoneColaboradorField, value) != true)) {
                    this.NumeroTelefoneColaboradorField = value;
                    this.RaisePropertyChanged("NumeroTelefoneColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public GIR.Integracao.ServicoColaborador.UnidadeOrganizacional UnidadeOrganizacionalColaborador {
            get {
                return this.UnidadeOrganizacionalColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeOrganizacionalColaboradorField, value) != true)) {
                    this.UnidadeOrganizacionalColaboradorField = value;
                    this.RaisePropertyChanged("UnidadeOrganizacionalColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string NomeGerenteColaborador {
            get {
                return this.NomeGerenteColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeGerenteColaboradorField, value) != true)) {
                    this.NomeGerenteColaboradorField = value;
                    this.RaisePropertyChanged("NomeGerenteColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string CPFColaborador {
            get {
                return this.CPFColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFColaboradorField, value) != true)) {
                    this.CPFColaboradorField = value;
                    this.RaisePropertyChanged("CPFColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool IsAtivo {
            get {
                return this.IsAtivoField;
            }
            set {
                if ((this.IsAtivoField.Equals(value) != true)) {
                    this.IsAtivoField = value;
                    this.RaisePropertyChanged("IsAtivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadeOrganizacional", Namespace="http://ws.cassi.com.br/v1/modelos/UnidadeOrganizacional")]
    [System.SerializableAttribute()]
    public partial class UnidadeOrganizacional : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoUnidadeOrganizacionalField;
        
        private string NomeUnidadeOrganizacionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailUnidadeOrganizacionalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoUnidadeOrganizacional {
            get {
                return this.CodigoUnidadeOrganizacionalField;
            }
            set {
                if ((this.CodigoUnidadeOrganizacionalField.Equals(value) != true)) {
                    this.CodigoUnidadeOrganizacionalField = value;
                    this.RaisePropertyChanged("CodigoUnidadeOrganizacional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NomeUnidadeOrganizacional {
            get {
                return this.NomeUnidadeOrganizacionalField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeUnidadeOrganizacionalField, value) != true)) {
                    this.NomeUnidadeOrganizacionalField = value;
                    this.RaisePropertyChanged("NomeUnidadeOrganizacional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string EmailUnidadeOrganizacional {
            get {
                return this.EmailUnidadeOrganizacionalField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailUnidadeOrganizacionalField, value) != true)) {
                    this.EmailUnidadeOrganizacionalField = value;
                    this.RaisePropertyChanged("EmailUnidadeOrganizacional");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/Servico.Erros")]
    [System.SerializableAttribute()]
    public partial class ServicoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cassi.com.br/v2/servicos/ServicoColaborador", ConfigurationName="ServicoColaborador.IServicoColaborador")]
    public interface IServicoColaborador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v2/servicos/ServicoColaborador/IServicoColaborador/ObterCo" +
            "laborador", ReplyAction="http://ws.cassi.com.br/v2/servicos/ServicoColaborador/IServicoColaborador/ObterCo" +
            "laboradorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoColaborador.ServicoException), Action="http://ws.cassi.com.br/v2/servicos/ServicoColaborador/IServicoColaborador/ObterCo" +
            "laborador", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/Servico.Erros")]
        GIR.Integracao.ServicoColaborador.RetornoColaborador ObterColaborador(string loginColaborador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v2/servicos/ServicoColaborador/IServicoColaborador/ObterFu" +
            "ncionarioPorMatricula", ReplyAction="http://ws.cassi.com.br/v2/servicos/ServicoColaborador/IServicoColaborador/ObterFu" +
            "ncionarioPorMatriculaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoColaborador.ServicoException), Action="http://ws.cassi.com.br/v2/servicos/ServicoColaborador/IServicoColaborador/ObterFu" +
            "ncionarioPorMatricula", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/Servico.Erros")]
        GIR.Integracao.ServicoColaborador.RetornoColaborador ObterFuncionarioPorMatricula(string matriculaFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v2/servicos/ServicoColaborador/IServicoColaborador/ObterCo" +
            "laboradorPorCPF", ReplyAction="http://ws.cassi.com.br/v2/servicos/ServicoColaborador/IServicoColaborador/ObterCo" +
            "laboradorPorCPFResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoColaborador.ServicoException), Action="http://ws.cassi.com.br/v2/servicos/ServicoColaborador/IServicoColaborador/ObterCo" +
            "laboradorPorCPF", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/Servico.Erros")]
        GIR.Integracao.ServicoColaborador.RetornoColaborador ObterColaboradorPorCPF(string cpfColaborador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v2/servicos/ServicoColaborador/IServicoColaborador/ListarC" +
            "olaborador", ReplyAction="http://ws.cassi.com.br/v2/servicos/ServicoColaborador/IServicoColaborador/ListarC" +
            "olaboradorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoColaborador.ServicoException), Action="http://ws.cassi.com.br/v2/servicos/ServicoColaborador/IServicoColaborador/ListarC" +
            "olaborador", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/Servico.Erros")]
        GIR.Integracao.ServicoColaborador.RetornoListaColaborador ListarColaborador(string nomeColaborador, bool somenteAtivos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoColaboradorChannel : GIR.Integracao.ServicoColaborador.IServicoColaborador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoColaboradorClient : System.ServiceModel.ClientBase<GIR.Integracao.ServicoColaborador.IServicoColaborador>, GIR.Integracao.ServicoColaborador.IServicoColaborador {
        
        public ServicoColaboradorClient() {
        }
        
        public ServicoColaboradorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoColaboradorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoColaboradorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoColaboradorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GIR.Integracao.ServicoColaborador.RetornoColaborador ObterColaborador(string loginColaborador) {
            return base.Channel.ObterColaborador(loginColaborador);
        }
        
        public GIR.Integracao.ServicoColaborador.RetornoColaborador ObterFuncionarioPorMatricula(string matriculaFuncionario) {
            return base.Channel.ObterFuncionarioPorMatricula(matriculaFuncionario);
        }
        
        public GIR.Integracao.ServicoColaborador.RetornoColaborador ObterColaboradorPorCPF(string cpfColaborador) {
            return base.Channel.ObterColaboradorPorCPF(cpfColaborador);
        }
        
        public GIR.Integracao.ServicoColaborador.RetornoListaColaborador ListarColaborador(string nomeColaborador, bool somenteAtivos) {
            return base.Channel.ListarColaborador(nomeColaborador, somenteAtivos);
        }
    }
}
