//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR.Integracao.ServicoFornecedor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fornecedor", Namespace="http://ws.cassi.com.br/V1/Fornecedor")]
    [System.SerializableAttribute()]
    public partial class fornecedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idFornecedorField;
        
        private string nomeFornecedorField;
        
        private string cpfCnpjFornecedorField;
        
        private GIR.Integracao.ServicoFornecedor.endereco enderecoField;
        
        private string telefoneComercialField;
        
        private string telefoneCelularField;
        
        private string emailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> idFornecedor {
            get {
                return this.idFornecedorField;
            }
            set {
                if ((this.idFornecedorField.Equals(value) != true)) {
                    this.idFornecedorField = value;
                    this.RaisePropertyChanged("idFornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomeFornecedor {
            get {
                return this.nomeFornecedorField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeFornecedorField, value) != true)) {
                    this.nomeFornecedorField = value;
                    this.RaisePropertyChanged("nomeFornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string cpfCnpjFornecedor {
            get {
                return this.cpfCnpjFornecedorField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfCnpjFornecedorField, value) != true)) {
                    this.cpfCnpjFornecedorField = value;
                    this.RaisePropertyChanged("cpfCnpjFornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public GIR.Integracao.ServicoFornecedor.endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string telefoneComercial {
            get {
                return this.telefoneComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoneComercialField, value) != true)) {
                    this.telefoneComercialField = value;
                    this.RaisePropertyChanged("telefoneComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string telefoneCelular {
            get {
                return this.telefoneCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoneCelularField, value) != true)) {
                    this.telefoneCelularField = value;
                    this.RaisePropertyChanged("telefoneCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="endereco", Namespace="http://ws.cassi.com.br/v1/endereco/")]
    [System.SerializableAttribute()]
    public partial class endereco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string logradouroField;
        
        private string numeroField;
        
        private string complementoField;
        
        private string cepField;
        
        private string bairroField;
        
        private string municipioField;
        
        private string estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.logradouroField, value) != true)) {
                    this.logradouroField = value;
                    this.RaisePropertyChanged("logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroField, value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string complemento {
            get {
                return this.complementoField;
            }
            set {
                if ((object.ReferenceEquals(this.complementoField, value) != true)) {
                    this.complementoField = value;
                    this.RaisePropertyChanged("complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                if ((object.ReferenceEquals(this.cepField, value) != true)) {
                    this.cepField = value;
                    this.RaisePropertyChanged("cep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                if ((object.ReferenceEquals(this.bairroField, value) != true)) {
                    this.bairroField = value;
                    this.RaisePropertyChanged("bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                if ((object.ReferenceEquals(this.municipioField, value) != true)) {
                    this.municipioField = value;
                    this.RaisePropertyChanged("municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cassi.com.br/V1/ServicoConsultaFornecedor/", ConfigurationName="ServicoFornecedor.ServicoConsultaFornecedor")]
    public interface ServicoConsultaFornecedor {
        
        // CODEGEN: Generating message contract since element name idFornecedor from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/V1/ServicoConsultaFornecedor/ListarFornecedor", ReplyAction="*")]
        GIR.Integracao.ServicoFornecedor.ListarFornecedorResponse ListarFornecedor(GIR.Integracao.ServicoFornecedor.ListarFornecedorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarFornecedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarFornecedor", Namespace="http://ws.cassi.com.br/V1/ServicoConsultaFornecedor/", Order=0)]
        public GIR.Integracao.ServicoFornecedor.ListarFornecedorRequestBody Body;
        
        public ListarFornecedorRequest() {
        }
        
        public ListarFornecedorRequest(GIR.Integracao.ServicoFornecedor.ListarFornecedorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ListarFornecedorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idFornecedor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomeFornecedor;
        
        public ListarFornecedorRequestBody() {
        }
        
        public ListarFornecedorRequestBody(string idFornecedor, string nomeFornecedor) {
            this.idFornecedor = idFornecedor;
            this.nomeFornecedor = nomeFornecedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarFornecedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarFornecedorResponse", Namespace="http://ws.cassi.com.br/V1/ServicoConsultaFornecedor/", Order=0)]
        public GIR.Integracao.ServicoFornecedor.ListarFornecedorResponseBody Body;
        
        public ListarFornecedorResponse() {
        }
        
        public ListarFornecedorResponse(GIR.Integracao.ServicoFornecedor.ListarFornecedorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ListarFornecedorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensagem;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public GIR.Integracao.ServicoFornecedor.fornecedor fornecedor;
        
        public ListarFornecedorResponseBody() {
        }
        
        public ListarFornecedorResponseBody(int codigo, string mensagem, GIR.Integracao.ServicoFornecedor.fornecedor fornecedor) {
            this.codigo = codigo;
            this.mensagem = mensagem;
            this.fornecedor = fornecedor;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoConsultaFornecedorChannel : GIR.Integracao.ServicoFornecedor.ServicoConsultaFornecedor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoConsultaFornecedorClient : System.ServiceModel.ClientBase<GIR.Integracao.ServicoFornecedor.ServicoConsultaFornecedor>, GIR.Integracao.ServicoFornecedor.ServicoConsultaFornecedor {
        
        public ServicoConsultaFornecedorClient() {
        }
        
        public ServicoConsultaFornecedorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoConsultaFornecedorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoConsultaFornecedorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoConsultaFornecedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoFornecedor.ListarFornecedorResponse GIR.Integracao.ServicoFornecedor.ServicoConsultaFornecedor.ListarFornecedor(GIR.Integracao.ServicoFornecedor.ListarFornecedorRequest request) {
            return base.Channel.ListarFornecedor(request);
        }
        
        public int ListarFornecedor(string idFornecedor, string nomeFornecedor, out string mensagem, out GIR.Integracao.ServicoFornecedor.fornecedor fornecedor) {
            GIR.Integracao.ServicoFornecedor.ListarFornecedorRequest inValue = new GIR.Integracao.ServicoFornecedor.ListarFornecedorRequest();
            inValue.Body = new GIR.Integracao.ServicoFornecedor.ListarFornecedorRequestBody();
            inValue.Body.idFornecedor = idFornecedor;
            inValue.Body.nomeFornecedor = nomeFornecedor;
            GIR.Integracao.ServicoFornecedor.ListarFornecedorResponse retVal = ((GIR.Integracao.ServicoFornecedor.ServicoConsultaFornecedor)(this)).ListarFornecedor(inValue);
            mensagem = retVal.Body.mensagem;
            fornecedor = retVal.Body.fornecedor;
            return retVal.Body.codigo;
        }
    }
}
