//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR.Integracao.ServicoUtilitarioConsulta {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class ObterMunicipioPorIbgeEstadoFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("mensagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class Municipio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cepField;
        
        private System.Nullable<int> idRegiaoField;
        
        private string idRegiaoSaudeField;
        
        private string nomeField;
        
        private System.Nullable<int> idMunicipioField;
        
        private Estado estadoField;
        
        private int codigoIbgeMunicipioField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
                this.RaisePropertyChanged("cep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> idRegiao {
            get {
                return this.idRegiaoField;
            }
            set {
                this.idRegiaoField = value;
                this.RaisePropertyChanged("idRegiao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string idRegiaoSaude {
            get {
                return this.idRegiaoSaudeField;
            }
            set {
                this.idRegiaoSaudeField = value;
                this.RaisePropertyChanged("idRegiaoSaude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<int> idMunicipio {
            get {
                return this.idMunicipioField;
            }
            set {
                this.idMunicipioField = value;
                this.RaisePropertyChanged("idMunicipio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public Estado estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int codigoIbgeMunicipio {
            get {
                return this.codigoIbgeMunicipioField;
            }
            set {
                this.codigoIbgeMunicipioField = value;
                this.RaisePropertyChanged("codigoIbgeMunicipio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class Estado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEstadoField;
        
        private string siglaField;
        
        private string nomeField;
        
        private int idPaisField;
        
        private string codigoTissField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sigla {
            get {
                return this.siglaField;
            }
            set {
                this.siglaField = value;
                this.RaisePropertyChanged("sigla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPais {
            get {
                return this.idPaisField;
            }
            set {
                this.idPaisField = value;
                this.RaisePropertyChanged("idPais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string codigoTiss {
            get {
                return this.codigoTissField;
            }
            set {
                this.codigoTissField = value;
                this.RaisePropertyChanged("codigoTiss");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class retornoListaUnidadesCassi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UnidadeEndereco[] unidadeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unidade", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UnidadeEndereco[] unidade {
            get {
                return this.unidadeField;
            }
            set {
                this.unidadeField = value;
                this.RaisePropertyChanged("unidade");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class UnidadeEndereco : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Unidade unidadeField;
        
        private Endereco enderecoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Unidade unidade {
            get {
                return this.unidadeField;
            }
            set {
                this.unidadeField = value;
                this.RaisePropertyChanged("unidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
                this.RaisePropertyChanged("endereco");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class Unidade : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private System.Nullable<int> codigoField;
        
        private bool codigoFieldSpecified;
        
        private string cnpjField;
        
        private string telefoneField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Unidade/", IsNullable=true, Order=0)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Unidade/", IsNullable=true, Order=1)]
        public System.Nullable<int> codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Unidade/", IsNullable=true, Order=2)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
                this.RaisePropertyChanged("cnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Unidade/", IsNullable=true, Order=3)]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
                this.RaisePropertyChanged("telefone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Unidade/", IsNullable=true, Order=4)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class Endereco : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bairroField;
        
        private string cepField;
        
        private System.Nullable<int> codigoIbgeMunicipioField;
        
        private bool codigoIbgeMunicipioFieldSpecified;
        
        private string complementoField;
        
        private System.Nullable<int> handleEstadoField;
        
        private bool handleEstadoFieldSpecified;
        
        private System.Nullable<int> handleMunicipioField;
        
        private bool handleMunicipioFieldSpecified;
        
        private string logradouroField;
        
        private string nomeEstadoField;
        
        private string nomeMunicipioField;
        
        private System.Nullable<int> numeroField;
        
        private bool numeroFieldSpecified;
        
        private string siglaEstadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Endereco/", IsNullable=true, Order=0)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Endereco/", IsNullable=true, Order=1)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
                this.RaisePropertyChanged("cep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Endereco/", IsNullable=true, Order=2)]
        public System.Nullable<int> codigoIbgeMunicipio {
            get {
                return this.codigoIbgeMunicipioField;
            }
            set {
                this.codigoIbgeMunicipioField = value;
                this.RaisePropertyChanged("codigoIbgeMunicipio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoIbgeMunicipioSpecified {
            get {
                return this.codigoIbgeMunicipioFieldSpecified;
            }
            set {
                this.codigoIbgeMunicipioFieldSpecified = value;
                this.RaisePropertyChanged("codigoIbgeMunicipioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Endereco/", IsNullable=true, Order=3)]
        public string complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
                this.RaisePropertyChanged("complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Endereco/", IsNullable=true, Order=4)]
        public System.Nullable<int> handleEstado {
            get {
                return this.handleEstadoField;
            }
            set {
                this.handleEstadoField = value;
                this.RaisePropertyChanged("handleEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool handleEstadoSpecified {
            get {
                return this.handleEstadoFieldSpecified;
            }
            set {
                this.handleEstadoFieldSpecified = value;
                this.RaisePropertyChanged("handleEstadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Endereco/", IsNullable=true, Order=5)]
        public System.Nullable<int> handleMunicipio {
            get {
                return this.handleMunicipioField;
            }
            set {
                this.handleMunicipioField = value;
                this.RaisePropertyChanged("handleMunicipio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool handleMunicipioSpecified {
            get {
                return this.handleMunicipioFieldSpecified;
            }
            set {
                this.handleMunicipioFieldSpecified = value;
                this.RaisePropertyChanged("handleMunicipioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Endereco/", IsNullable=true, Order=6)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
                this.RaisePropertyChanged("logradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Endereco/", IsNullable=true, Order=7)]
        public string nomeEstado {
            get {
                return this.nomeEstadoField;
            }
            set {
                this.nomeEstadoField = value;
                this.RaisePropertyChanged("nomeEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Endereco/", IsNullable=true, Order=8)]
        public string nomeMunicipio {
            get {
                return this.nomeMunicipioField;
            }
            set {
                this.nomeMunicipioField = value;
                this.RaisePropertyChanged("nomeMunicipio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Endereco/", IsNullable=true, Order=9)]
        public System.Nullable<int> numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified {
            get {
                return this.numeroFieldSpecified;
            }
            set {
                this.numeroFieldSpecified = value;
                this.RaisePropertyChanged("numeroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.cassi.com.br/v1/Endereco/", IsNullable=true, Order=10)]
        public string siglaEstado {
            get {
                return this.siglaEstadoField;
            }
            set {
                this.siglaEstadoField = value;
                this.RaisePropertyChanged("siglaEstado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class listarFiliaisCassiFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class obterEnderecoPorCepFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class listarEstadoCivilFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class listarTipoNaturezaDocumentoFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string listarTipoNaturezaDocumentoFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listarTipoNaturezaDocumentoFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string listarTipoNaturezaDocumentoFault1 {
            get {
                return this.listarTipoNaturezaDocumentoFault1Field;
            }
            set {
                this.listarTipoNaturezaDocumentoFault1Field = value;
                this.RaisePropertyChanged("listarTipoNaturezaDocumentoFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class listarCbosFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string listarCbosFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listarCbosFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string listarCbosFault1 {
            get {
                return this.listarCbosFault1Field;
            }
            set {
                this.listarCbosFault1Field = value;
                this.RaisePropertyChanged("listarCbosFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", ConfigurationName="ServicoUtilitarioConsulta.UtilitarioConsulta")]
    public interface UtilitarioConsulta {
        
        // CODEGEN: Generating message contract since the wrapper name (ListarUnidadesCassiPorUFResponse) of message listarUnidadesCassiPorUFResponse does not match the default value (listarUnidadesCassiPorUF)
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/listarUnidadesCassiPorUF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GIR.Integracao.ServicoUtilitarioConsulta.listarUnidadesCassiPorUFResponse listarUnidadesCassiPorUF(GIR.Integracao.ServicoUtilitarioConsulta.listarUnidadesCassiPorUFRequest request);
        
        // CODEGEN: Parameter 'retornoListaEstados' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/listarEstados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="retornoListaEstados")]
        GIR.Integracao.ServicoUtilitarioConsulta.listarEstadosResponse listarEstados(GIR.Integracao.ServicoUtilitarioConsulta.listarEstadosRequest request);
        
        // CODEGEN: Parameter 'retornoListaMunicipios' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/listarMunicipiosPorEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="retornoListaMunicipios")]
        GIR.Integracao.ServicoUtilitarioConsulta.listarMunicipiosPorEstadoResponse listarMunicipiosPorEstado(GIR.Integracao.ServicoUtilitarioConsulta.listarMunicipiosPorEstadoRequest request);
        
        // CODEGEN: Parameter 'municipio' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/obterMunicipio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="municipio")]
        GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioResponse obterMunicipio(GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioRequest request);
        
        // CODEGEN: Parameter 'estado' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/obterEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="estado")]
        GIR.Integracao.ServicoUtilitarioConsulta.obterEstadoResponse obterEstado(GIR.Integracao.ServicoUtilitarioConsulta.obterEstadoRequest request);
        
        // CODEGEN: Parameter 'retornoMunicipio' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/obterMunicipioPorIbgeEstado", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoUtilitarioConsulta.ObterMunicipioPorIbgeEstadoFault), Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/obterMunicipioPorIbgeEstado", Name="obterMunicipioPorIbgeEstadoFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="retornoMunicipio")]
        GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioPorIbgeEstadoResponse obterMunicipioPorIbgeEstado(GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioPorIbgeEstadoRequest request);
        
        // CODEGEN: Parameter 'retornoEspecializacao' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/listarEspecializacoes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="retornoEspecializacao")]
        GIR.Integracao.ServicoUtilitarioConsulta.listarEspecializacoesResponse listarEspecializacoes(GIR.Integracao.ServicoUtilitarioConsulta.listarEspecializacoesRequest request);
        
        // CODEGEN: Parameter 'retornoFiliaisCassi' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/listarFiliaisCassi", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoUtilitarioConsulta.listarFiliaisCassiFault), Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/listarFiliaisCassi", Name="listarFiliaisCassiFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="retornoFiliaisCassi")]
        GIR.Integracao.ServicoUtilitarioConsulta.listarFiliaisCassiResponse listarFiliaisCassi(GIR.Integracao.ServicoUtilitarioConsulta.listarFiliaisCassiRequest request);
        
        // CODEGEN: Parameter 'RetornoObterEnderecoPorCep' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/obterEnderecoPorCep", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoUtilitarioConsulta.obterEnderecoPorCepFault), Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/obterEnderecoPorCep", Name="obterEnderecoPorCepFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RetornoObterEnderecoPorCep")]
        GIR.Integracao.ServicoUtilitarioConsulta.obterEnderecoPorCepResponse obterEnderecoPorCep(GIR.Integracao.ServicoUtilitarioConsulta.obterEnderecoPorCepRequest request);
        
        // CODEGEN: Parameter 'retornoListarEstadoCivil' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/listarEstadoCivil", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoUtilitarioConsulta.listarEstadoCivilFault), Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/listarEstadoCivil", Name="listarEstadoCivilFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="retornoListarEstadoCivil")]
        GIR.Integracao.ServicoUtilitarioConsulta.listarEstadoCivilResponse listarEstadoCivil(GIR.Integracao.ServicoUtilitarioConsulta.listarEstadoCivilRequest request);
        
        // CODEGEN: Parameter 'retornoListarTipoNaturezaDocumento' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/listarTipoNaturezaDocumento", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoUtilitarioConsulta.listarTipoNaturezaDocumentoFault), Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/listarTipoNaturezaDocumento", Name="listarTipoNaturezaDocumentoFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="retornoListarTipoNaturezaDocumento")]
        GIR.Integracao.ServicoUtilitarioConsulta.listarTipoNaturezaDocumentoResponse listarTipoNaturezaDocumento(GIR.Integracao.ServicoUtilitarioConsulta.listarTipoNaturezaDocumentoRequest request);
        
        // CODEGEN: Parameter 'retornoListarCbos' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/listarCbos", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoUtilitarioConsulta.listarCbosFault), Action="http://ws.cassi.com.br/v1/UtilitarioConsulta/listarCbos", Name="listarCbosFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="retornoListarCbos")]
        GIR.Integracao.ServicoUtilitarioConsulta.listarCbosResponse listarCbos(GIR.Integracao.ServicoUtilitarioConsulta.listarCbosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUnidadesCassiPorUF", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarUnidadesCassiPorUFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ufEstado;
        
        public listarUnidadesCassiPorUFRequest() {
        }
        
        public listarUnidadesCassiPorUFRequest(string ufEstado) {
            this.ufEstado = ufEstado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarUnidadesCassiPorUFResponse", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarUnidadesCassiPorUFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("retornoListaUnidades", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIR.Integracao.ServicoUtilitarioConsulta.retornoListaUnidadesCassi[] retornoListaUnidades;
        
        public listarUnidadesCassiPorUFResponse() {
        }
        
        public listarUnidadesCassiPorUFResponse(GIR.Integracao.ServicoUtilitarioConsulta.retornoListaUnidadesCassi[] retornoListaUnidades) {
            this.retornoListaUnidades = retornoListaUnidades;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEstados", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarEstadosRequest {
        
        public listarEstadosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEstadosResponse", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarEstadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("retornoListaEstados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIR.Integracao.ServicoUtilitarioConsulta.Estado[] retornoListaEstados;
        
        public listarEstadosResponse() {
        }
        
        public listarEstadosResponse(GIR.Integracao.ServicoUtilitarioConsulta.Estado[] retornoListaEstados) {
            this.retornoListaEstados = retornoListaEstados;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMunicipiosPorEstado", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarMunicipiosPorEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEstado;
        
        public listarMunicipiosPorEstadoRequest() {
        }
        
        public listarMunicipiosPorEstadoRequest(int idEstado) {
            this.idEstado = idEstado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMunicipiosPorEstadoResponse", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarMunicipiosPorEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("retornoListaMunicipios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIR.Integracao.ServicoUtilitarioConsulta.Municipio[] retornoListaMunicipios;
        
        public listarMunicipiosPorEstadoResponse() {
        }
        
        public listarMunicipiosPorEstadoResponse(GIR.Integracao.ServicoUtilitarioConsulta.Municipio[] retornoListaMunicipios) {
            this.retornoListaMunicipios = retornoListaMunicipios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterMunicipio", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class obterMunicipioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMunicipio;
        
        public obterMunicipioRequest() {
        }
        
        public obterMunicipioRequest(int idMunicipio) {
            this.idMunicipio = idMunicipio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterMunicipioResponse", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class obterMunicipioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIR.Integracao.ServicoUtilitarioConsulta.Municipio municipio;
        
        public obterMunicipioResponse() {
        }
        
        public obterMunicipioResponse(GIR.Integracao.ServicoUtilitarioConsulta.Municipio municipio) {
            this.municipio = municipio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterEstado", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class obterEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEstado;
        
        public obterEstadoRequest() {
        }
        
        public obterEstadoRequest(int idEstado) {
            this.idEstado = idEstado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterEstadoResponse", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class obterEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIR.Integracao.ServicoUtilitarioConsulta.Estado estado;
        
        public obterEstadoResponse() {
        }
        
        public obterEstadoResponse(GIR.Integracao.ServicoUtilitarioConsulta.Estado estado) {
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterMunicipioPorIbgeEstado", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class obterMunicipioPorIbgeEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoIbge;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeMunicipio;
        
        public obterMunicipioPorIbgeEstadoRequest() {
        }
        
        public obterMunicipioPorIbgeEstadoRequest(int codigoIbge, string nomeMunicipio) {
            this.codigoIbge = codigoIbge;
            this.nomeMunicipio = nomeMunicipio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterMunicipioPorIbgeEstadoResponse", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class obterMunicipioPorIbgeEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIR.Integracao.ServicoUtilitarioConsulta.Municipio retornoMunicipio;
        
        public obterMunicipioPorIbgeEstadoResponse() {
        }
        
        public obterMunicipioPorIbgeEstadoResponse(GIR.Integracao.ServicoUtilitarioConsulta.Municipio retornoMunicipio) {
            this.retornoMunicipio = retornoMunicipio;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class Especializacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEspecializacaoField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idEspecializacao {
            get {
                return this.idEspecializacaoField;
            }
            set {
                this.idEspecializacaoField = value;
                this.RaisePropertyChanged("idEspecializacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEspecializacoes", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarEspecializacoesRequest {
        
        public listarEspecializacoesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEspecializacoesResponse", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarEspecializacoesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("retornoEspecializacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIR.Integracao.ServicoUtilitarioConsulta.Especializacao[] retornoEspecializacao;
        
        public listarEspecializacoesResponse() {
        }
        
        public listarEspecializacoesResponse(GIR.Integracao.ServicoUtilitarioConsulta.Especializacao[] retornoEspecializacao) {
            this.retornoEspecializacao = retornoEspecializacao;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class Filial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idFilialField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idFilial {
            get {
                return this.idFilialField;
            }
            set {
                this.idFilialField = value;
                this.RaisePropertyChanged("idFilial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarFiliaisCassi", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarFiliaisCassiRequest {
        
        public listarFiliaisCassiRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarFiliaisCassiResponse", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarFiliaisCassiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("retornoFiliaisCassi", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIR.Integracao.ServicoUtilitarioConsulta.Filial[] retornoFiliaisCassi;
        
        public listarFiliaisCassiResponse() {
        }
        
        public listarFiliaisCassiResponse(GIR.Integracao.ServicoUtilitarioConsulta.Filial[] retornoFiliaisCassi) {
            this.retornoFiliaisCassi = retornoFiliaisCassi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterEnderecoPorCep", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class obterEnderecoPorCepRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cep;
        
        public obterEnderecoPorCepRequest() {
        }
        
        public obterEnderecoPorCepRequest(string cep) {
            this.cep = cep;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterEnderecoPorCepResponse", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class obterEnderecoPorCepResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIR.Integracao.ServicoUtilitarioConsulta.Endereco RetornoObterEnderecoPorCep;
        
        public obterEnderecoPorCepResponse() {
        }
        
        public obterEnderecoPorCepResponse(GIR.Integracao.ServicoUtilitarioConsulta.Endereco RetornoObterEnderecoPorCep) {
            this.RetornoObterEnderecoPorCep = RetornoObterEnderecoPorCep;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class EstadoCivil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEstadoCivilField;
        
        private bool idEstadoCivilFieldSpecified;
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private System.Nullable<int> codigoArhField;
        
        private bool codigoArhFieldSpecified;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idEstadoCivil {
            get {
                return this.idEstadoCivilField;
            }
            set {
                this.idEstadoCivilField = value;
                this.RaisePropertyChanged("idEstadoCivil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoCivilSpecified {
            get {
                return this.idEstadoCivilFieldSpecified;
            }
            set {
                this.idEstadoCivilFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoCivilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> codigoArh {
            get {
                return this.codigoArhField;
            }
            set {
                this.codigoArhField = value;
                this.RaisePropertyChanged("codigoArh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoArhSpecified {
            get {
                return this.codigoArhFieldSpecified;
            }
            set {
                this.codigoArhFieldSpecified = value;
                this.RaisePropertyChanged("codigoArhSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEstadoCivil", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarEstadoCivilRequest {
        
        public listarEstadoCivilRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEstadoCivilResponse", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarEstadoCivilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("retornoListarEstadoCivil", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIR.Integracao.ServicoUtilitarioConsulta.EstadoCivil[] retornoListarEstadoCivil;
        
        public listarEstadoCivilResponse() {
        }
        
        public listarEstadoCivilResponse(GIR.Integracao.ServicoUtilitarioConsulta.EstadoCivil[] retornoListarEstadoCivil) {
            this.retornoListarEstadoCivil = retornoListarEstadoCivil;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class NaturezaDocumento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idNaturezaDocumentoField;
        
        private string descricaoField;
        
        private int codigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idNaturezaDocumento {
            get {
                return this.idNaturezaDocumentoField;
            }
            set {
                this.idNaturezaDocumentoField = value;
                this.RaisePropertyChanged("idNaturezaDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTipoNaturezaDocumento", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarTipoNaturezaDocumentoRequest {
        
        public listarTipoNaturezaDocumentoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTipoNaturezaDocumentoResponse", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarTipoNaturezaDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("retornoListarTipoNaturezaDocumento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIR.Integracao.ServicoUtilitarioConsulta.NaturezaDocumento[] retornoListarTipoNaturezaDocumento;
        
        public listarTipoNaturezaDocumentoResponse() {
        }
        
        public listarTipoNaturezaDocumentoResponse(GIR.Integracao.ServicoUtilitarioConsulta.NaturezaDocumento[] retornoListarTipoNaturezaDocumento) {
            this.retornoListarTipoNaturezaDocumento = retornoListarTipoNaturezaDocumento;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/")]
    public partial class Cbo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idCboField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idCbo {
            get {
                return this.idCboField;
            }
            set {
                this.idCboField = value;
                this.RaisePropertyChanged("idCbo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCbos", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarCbosRequest {
        
        public listarCbosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCbosResponse", WrapperNamespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", IsWrapped=true)]
    public partial class listarCbosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cassi.com.br/v1/UtilitarioConsulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("retornoListarCbos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIR.Integracao.ServicoUtilitarioConsulta.Cbo[] retornoListarCbos;
        
        public listarCbosResponse() {
        }
        
        public listarCbosResponse(GIR.Integracao.ServicoUtilitarioConsulta.Cbo[] retornoListarCbos) {
            this.retornoListarCbos = retornoListarCbos;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UtilitarioConsultaChannel : GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilitarioConsultaClient : System.ServiceModel.ClientBase<GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta>, GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta {
        
        public UtilitarioConsultaClient() {
        }
        
        public UtilitarioConsultaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilitarioConsultaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilitarioConsultaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilitarioConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoUtilitarioConsulta.listarUnidadesCassiPorUFResponse GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta.listarUnidadesCassiPorUF(GIR.Integracao.ServicoUtilitarioConsulta.listarUnidadesCassiPorUFRequest request) {
            return base.Channel.listarUnidadesCassiPorUF(request);
        }
        
        public GIR.Integracao.ServicoUtilitarioConsulta.retornoListaUnidadesCassi[] listarUnidadesCassiPorUF(string ufEstado) {
            GIR.Integracao.ServicoUtilitarioConsulta.listarUnidadesCassiPorUFRequest inValue = new GIR.Integracao.ServicoUtilitarioConsulta.listarUnidadesCassiPorUFRequest();
            inValue.ufEstado = ufEstado;
            GIR.Integracao.ServicoUtilitarioConsulta.listarUnidadesCassiPorUFResponse retVal = ((GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta)(this)).listarUnidadesCassiPorUF(inValue);
            return retVal.retornoListaUnidades;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoUtilitarioConsulta.listarEstadosResponse GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta.listarEstados(GIR.Integracao.ServicoUtilitarioConsulta.listarEstadosRequest request) {
            return base.Channel.listarEstados(request);
        }
        
        public GIR.Integracao.ServicoUtilitarioConsulta.Estado[] listarEstados() {
            GIR.Integracao.ServicoUtilitarioConsulta.listarEstadosRequest inValue = new GIR.Integracao.ServicoUtilitarioConsulta.listarEstadosRequest();
            GIR.Integracao.ServicoUtilitarioConsulta.listarEstadosResponse retVal = ((GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta)(this)).listarEstados(inValue);
            return retVal.retornoListaEstados;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoUtilitarioConsulta.listarMunicipiosPorEstadoResponse GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta.listarMunicipiosPorEstado(GIR.Integracao.ServicoUtilitarioConsulta.listarMunicipiosPorEstadoRequest request) {
            return base.Channel.listarMunicipiosPorEstado(request);
        }
        
        public GIR.Integracao.ServicoUtilitarioConsulta.Municipio[] listarMunicipiosPorEstado(int idEstado) {
            GIR.Integracao.ServicoUtilitarioConsulta.listarMunicipiosPorEstadoRequest inValue = new GIR.Integracao.ServicoUtilitarioConsulta.listarMunicipiosPorEstadoRequest();
            inValue.idEstado = idEstado;
            GIR.Integracao.ServicoUtilitarioConsulta.listarMunicipiosPorEstadoResponse retVal = ((GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta)(this)).listarMunicipiosPorEstado(inValue);
            return retVal.retornoListaMunicipios;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioResponse GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta.obterMunicipio(GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioRequest request) {
            return base.Channel.obterMunicipio(request);
        }
        
        public GIR.Integracao.ServicoUtilitarioConsulta.Municipio obterMunicipio(int idMunicipio) {
            GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioRequest inValue = new GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioRequest();
            inValue.idMunicipio = idMunicipio;
            GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioResponse retVal = ((GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta)(this)).obterMunicipio(inValue);
            return retVal.municipio;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoUtilitarioConsulta.obterEstadoResponse GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta.obterEstado(GIR.Integracao.ServicoUtilitarioConsulta.obterEstadoRequest request) {
            return base.Channel.obterEstado(request);
        }
        
        public GIR.Integracao.ServicoUtilitarioConsulta.Estado obterEstado(int idEstado) {
            GIR.Integracao.ServicoUtilitarioConsulta.obterEstadoRequest inValue = new GIR.Integracao.ServicoUtilitarioConsulta.obterEstadoRequest();
            inValue.idEstado = idEstado;
            GIR.Integracao.ServicoUtilitarioConsulta.obterEstadoResponse retVal = ((GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta)(this)).obterEstado(inValue);
            return retVal.estado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioPorIbgeEstadoResponse GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta.obterMunicipioPorIbgeEstado(GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioPorIbgeEstadoRequest request) {
            return base.Channel.obterMunicipioPorIbgeEstado(request);
        }
        
        public GIR.Integracao.ServicoUtilitarioConsulta.Municipio obterMunicipioPorIbgeEstado(int codigoIbge, string nomeMunicipio) {
            GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioPorIbgeEstadoRequest inValue = new GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioPorIbgeEstadoRequest();
            inValue.codigoIbge = codigoIbge;
            inValue.nomeMunicipio = nomeMunicipio;
            GIR.Integracao.ServicoUtilitarioConsulta.obterMunicipioPorIbgeEstadoResponse retVal = ((GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta)(this)).obterMunicipioPorIbgeEstado(inValue);
            return retVal.retornoMunicipio;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoUtilitarioConsulta.listarEspecializacoesResponse GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta.listarEspecializacoes(GIR.Integracao.ServicoUtilitarioConsulta.listarEspecializacoesRequest request) {
            return base.Channel.listarEspecializacoes(request);
        }
        
        public GIR.Integracao.ServicoUtilitarioConsulta.Especializacao[] listarEspecializacoes() {
            GIR.Integracao.ServicoUtilitarioConsulta.listarEspecializacoesRequest inValue = new GIR.Integracao.ServicoUtilitarioConsulta.listarEspecializacoesRequest();
            GIR.Integracao.ServicoUtilitarioConsulta.listarEspecializacoesResponse retVal = ((GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta)(this)).listarEspecializacoes(inValue);
            return retVal.retornoEspecializacao;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoUtilitarioConsulta.listarFiliaisCassiResponse GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta.listarFiliaisCassi(GIR.Integracao.ServicoUtilitarioConsulta.listarFiliaisCassiRequest request) {
            return base.Channel.listarFiliaisCassi(request);
        }
        
        public GIR.Integracao.ServicoUtilitarioConsulta.Filial[] listarFiliaisCassi() {
            GIR.Integracao.ServicoUtilitarioConsulta.listarFiliaisCassiRequest inValue = new GIR.Integracao.ServicoUtilitarioConsulta.listarFiliaisCassiRequest();
            GIR.Integracao.ServicoUtilitarioConsulta.listarFiliaisCassiResponse retVal = ((GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta)(this)).listarFiliaisCassi(inValue);
            return retVal.retornoFiliaisCassi;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoUtilitarioConsulta.obterEnderecoPorCepResponse GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta.obterEnderecoPorCep(GIR.Integracao.ServicoUtilitarioConsulta.obterEnderecoPorCepRequest request) {
            return base.Channel.obterEnderecoPorCep(request);
        }
        
        public GIR.Integracao.ServicoUtilitarioConsulta.Endereco obterEnderecoPorCep(string cep) {
            GIR.Integracao.ServicoUtilitarioConsulta.obterEnderecoPorCepRequest inValue = new GIR.Integracao.ServicoUtilitarioConsulta.obterEnderecoPorCepRequest();
            inValue.cep = cep;
            GIR.Integracao.ServicoUtilitarioConsulta.obterEnderecoPorCepResponse retVal = ((GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta)(this)).obterEnderecoPorCep(inValue);
            return retVal.RetornoObterEnderecoPorCep;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoUtilitarioConsulta.listarEstadoCivilResponse GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta.listarEstadoCivil(GIR.Integracao.ServicoUtilitarioConsulta.listarEstadoCivilRequest request) {
            return base.Channel.listarEstadoCivil(request);
        }
        
        public GIR.Integracao.ServicoUtilitarioConsulta.EstadoCivil[] listarEstadoCivil() {
            GIR.Integracao.ServicoUtilitarioConsulta.listarEstadoCivilRequest inValue = new GIR.Integracao.ServicoUtilitarioConsulta.listarEstadoCivilRequest();
            GIR.Integracao.ServicoUtilitarioConsulta.listarEstadoCivilResponse retVal = ((GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta)(this)).listarEstadoCivil(inValue);
            return retVal.retornoListarEstadoCivil;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoUtilitarioConsulta.listarTipoNaturezaDocumentoResponse GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta.listarTipoNaturezaDocumento(GIR.Integracao.ServicoUtilitarioConsulta.listarTipoNaturezaDocumentoRequest request) {
            return base.Channel.listarTipoNaturezaDocumento(request);
        }
        
        public GIR.Integracao.ServicoUtilitarioConsulta.NaturezaDocumento[] listarTipoNaturezaDocumento() {
            GIR.Integracao.ServicoUtilitarioConsulta.listarTipoNaturezaDocumentoRequest inValue = new GIR.Integracao.ServicoUtilitarioConsulta.listarTipoNaturezaDocumentoRequest();
            GIR.Integracao.ServicoUtilitarioConsulta.listarTipoNaturezaDocumentoResponse retVal = ((GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta)(this)).listarTipoNaturezaDocumento(inValue);
            return retVal.retornoListarTipoNaturezaDocumento;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIR.Integracao.ServicoUtilitarioConsulta.listarCbosResponse GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta.listarCbos(GIR.Integracao.ServicoUtilitarioConsulta.listarCbosRequest request) {
            return base.Channel.listarCbos(request);
        }
        
        public GIR.Integracao.ServicoUtilitarioConsulta.Cbo[] listarCbos() {
            GIR.Integracao.ServicoUtilitarioConsulta.listarCbosRequest inValue = new GIR.Integracao.ServicoUtilitarioConsulta.listarCbosRequest();
            GIR.Integracao.ServicoUtilitarioConsulta.listarCbosResponse retVal = ((GIR.Integracao.ServicoUtilitarioConsulta.UtilitarioConsulta)(this)).listarCbos(inValue);
            return retVal.retornoListarCbos;
        }
    }
}
