//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR.Integracao.ServicoUnidadeOrganizacional {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Retorno", Namespace="http://ws.cassi.com.br/v1/retornos/Retorno")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GIR.Integracao.ServicoUnidadeOrganizacional.RetornoEstruturaOrganizacional))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GIR.Integracao.ServicoUnidadeOrganizacional.RetornoUnidadeOrganizacional))]
    public partial class Retorno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoEstruturaOrganizacional", Namespace="http://ws.cassi.com.br/v1/retornos/RetornoEstruturaOrganizacional")]
    [System.SerializableAttribute()]
    public partial class RetornoEstruturaOrganizacional : GIR.Integracao.ServicoUnidadeOrganizacional.Retorno {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoUnidadeOrganizacional.EstruturaOrganizacional EstruturaOrganizacionalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoUnidadeOrganizacional.EstruturaOrganizacional EstruturaOrganizacional {
            get {
                return this.EstruturaOrganizacionalField;
            }
            set {
                if ((object.ReferenceEquals(this.EstruturaOrganizacionalField, value) != true)) {
                    this.EstruturaOrganizacionalField = value;
                    this.RaisePropertyChanged("EstruturaOrganizacional");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoUnidadeOrganizacional", Namespace="http://ws.cassi.com.br/v1/retornos/RetornoUnidadeOrganizacional")]
    [System.SerializableAttribute()]
    public partial class RetornoUnidadeOrganizacional : GIR.Integracao.ServicoUnidadeOrganizacional.Retorno {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoUnidadeOrganizacional.UnidadeOrganizacional UnidadeOrganizacionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoUnidadeOrganizacional.UnidadeOrganizacional UnidadeOrganizacionalSuperiorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoUnidadeOrganizacional.UnidadeOrganizacional UnidadeOrganizacional {
            get {
                return this.UnidadeOrganizacionalField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeOrganizacionalField, value) != true)) {
                    this.UnidadeOrganizacionalField = value;
                    this.RaisePropertyChanged("UnidadeOrganizacional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoUnidadeOrganizacional.UnidadeOrganizacional UnidadeOrganizacionalSuperior {
            get {
                return this.UnidadeOrganizacionalSuperiorField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeOrganizacionalSuperiorField, value) != true)) {
                    this.UnidadeOrganizacionalSuperiorField = value;
                    this.RaisePropertyChanged("UnidadeOrganizacionalSuperior");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadeOrganizacional", Namespace="http://ws.cassi.com.br/v1/modelos/UnidadeOrganizacional")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GIR.Integracao.ServicoUnidadeOrganizacional.EstruturaOrganizacional))]
    public partial class UnidadeOrganizacional : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoUnidadeOrganizacionalField;
        
        private string NomeUnidadeOrganizacionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailUnidadeOrganizacionalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoUnidadeOrganizacional {
            get {
                return this.CodigoUnidadeOrganizacionalField;
            }
            set {
                if ((this.CodigoUnidadeOrganizacionalField.Equals(value) != true)) {
                    this.CodigoUnidadeOrganizacionalField = value;
                    this.RaisePropertyChanged("CodigoUnidadeOrganizacional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NomeUnidadeOrganizacional {
            get {
                return this.NomeUnidadeOrganizacionalField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeUnidadeOrganizacionalField, value) != true)) {
                    this.NomeUnidadeOrganizacionalField = value;
                    this.RaisePropertyChanged("NomeUnidadeOrganizacional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string EmailUnidadeOrganizacional {
            get {
                return this.EmailUnidadeOrganizacionalField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailUnidadeOrganizacionalField, value) != true)) {
                    this.EmailUnidadeOrganizacionalField = value;
                    this.RaisePropertyChanged("EmailUnidadeOrganizacional");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstruturaOrganizacional", Namespace="http://ws.cassi.com.br/v1/modelos/EstruturaOrganizacional")]
    [System.SerializableAttribute()]
    public partial class EstruturaOrganizacional : GIR.Integracao.ServicoUnidadeOrganizacional.UnidadeOrganizacional {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoUnidadeOrganizacional.UnidadeOrganizacional UnidadeOrganizacionalSuperiorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoUnidadeOrganizacional.EstruturaOrganizacional[] UnidadesOrganizacionaisSubordinadasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoUnidadeOrganizacional.UnidadeOrganizacional UnidadeOrganizacionalSuperior {
            get {
                return this.UnidadeOrganizacionalSuperiorField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeOrganizacionalSuperiorField, value) != true)) {
                    this.UnidadeOrganizacionalSuperiorField = value;
                    this.RaisePropertyChanged("UnidadeOrganizacionalSuperior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoUnidadeOrganizacional.EstruturaOrganizacional[] UnidadesOrganizacionaisSubordinadas {
            get {
                return this.UnidadesOrganizacionaisSubordinadasField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadesOrganizacionaisSubordinadasField, value) != true)) {
                    this.UnidadesOrganizacionaisSubordinadasField = value;
                    this.RaisePropertyChanged("UnidadesOrganizacionaisSubordinadas");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/Servico.Erros")]
    [System.SerializableAttribute()]
    public partial class ServicoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cassi.com.br/v1/servicos/ServicoUnidadeOrganizacional", ConfigurationName="ServicoUnidadeOrganizacional.IServicoUnidadeOrganizacional")]
    public interface IServicoUnidadeOrganizacional {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/servicos/ServicoUnidadeOrganizacional/IServicoUnidadeOr" +
            "ganizacional/ObterUnidadeOrganizacional", ReplyAction="http://ws.cassi.com.br/v1/servicos/ServicoUnidadeOrganizacional/IServicoUnidadeOr" +
            "ganizacional/ObterUnidadeOrganizacionalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoUnidadeOrganizacional.ServicoException), Action="http://ws.cassi.com.br/v1/servicos/ServicoUnidadeOrganizacional/IServicoUnidadeOr" +
            "ganizacional/ObterUnidadeOrganizacionalServicoExceptionFault", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/Servico.Erros")]
        GIR.Integracao.ServicoUnidadeOrganizacional.RetornoUnidadeOrganizacional ObterUnidadeOrganizacional(int codigoUnidadeOrganizacional);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cassi.com.br/v1/servicos/ServicoUnidadeOrganizacional/IServicoUnidadeOr" +
            "ganizacional/ObterEstruturaOrganizacional", ReplyAction="http://ws.cassi.com.br/v1/servicos/ServicoUnidadeOrganizacional/IServicoUnidadeOr" +
            "ganizacional/ObterEstruturaOrganizacionalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoUnidadeOrganizacional.ServicoException), Action="http://ws.cassi.com.br/v1/servicos/ServicoUnidadeOrganizacional/IServicoUnidadeOr" +
            "ganizacional/ObterEstruturaOrganizacionalServicoExceptionFault", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/Servico.Erros")]
        GIR.Integracao.ServicoUnidadeOrganizacional.RetornoEstruturaOrganizacional ObterEstruturaOrganizacional(int codigoUnidadeOrganizacional);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoUnidadeOrganizacionalChannel : GIR.Integracao.ServicoUnidadeOrganizacional.IServicoUnidadeOrganizacional, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoUnidadeOrganizacionalClient : System.ServiceModel.ClientBase<GIR.Integracao.ServicoUnidadeOrganizacional.IServicoUnidadeOrganizacional>, GIR.Integracao.ServicoUnidadeOrganizacional.IServicoUnidadeOrganizacional {
        
        public ServicoUnidadeOrganizacionalClient() {
        }
        
        public ServicoUnidadeOrganizacionalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoUnidadeOrganizacionalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoUnidadeOrganizacionalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoUnidadeOrganizacionalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GIR.Integracao.ServicoUnidadeOrganizacional.RetornoUnidadeOrganizacional ObterUnidadeOrganizacional(int codigoUnidadeOrganizacional) {
            return base.Channel.ObterUnidadeOrganizacional(codigoUnidadeOrganizacional);
        }
        
        public GIR.Integracao.ServicoUnidadeOrganizacional.RetornoEstruturaOrganizacional ObterEstruturaOrganizacional(int codigoUnidadeOrganizacional) {
            return base.Channel.ObterEstruturaOrganizacional(codigoUnidadeOrganizacional);
        }
    }
}
