//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR.Integracao.ServicoGASC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Retorno", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Retornos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GIR.Integracao.ServicoGASC.RetornoPerfisUsuario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GIR.Integracao.ServicoGASC.RetornoDadosComplementaresUsuario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GIR.Integracao.ServicoGASC.RetornoUsuarios))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GIR.Integracao.ServicoGASC.RetornoSistema))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GIR.Integracao.ServicoGASC.RetornoUsuario))]
    public partial class Retorno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoPerfisUsuario", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Retornos")]
    [System.SerializableAttribute()]
    public partial class RetornoPerfisUsuario : GIR.Integracao.ServicoGASC.Retorno {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoGASC.PerfilUsuario[] PerfisField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoGASC.PerfilUsuario[] Perfis {
            get {
                return this.PerfisField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfisField, value) != true)) {
                    this.PerfisField = value;
                    this.RaisePropertyChanged("Perfis");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoDadosComplementaresUsuario", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Retornos")]
    [System.SerializableAttribute()]
    public partial class RetornoDadosComplementaresUsuario : GIR.Integracao.ServicoGASC.Retorno {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoGASC.DadoComplementarUsuario[] DadosComplementaresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoGASC.DadoComplementarUsuario[] DadosComplementares {
            get {
                return this.DadosComplementaresField;
            }
            set {
                if ((object.ReferenceEquals(this.DadosComplementaresField, value) != true)) {
                    this.DadosComplementaresField = value;
                    this.RaisePropertyChanged("DadosComplementares");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoUsuarios", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Retornos")]
    [System.SerializableAttribute()]
    public partial class RetornoUsuarios : GIR.Integracao.ServicoGASC.Retorno {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoGASC.Usuario[] UsuariosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoGASC.Usuario[] Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoSistema", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Retornos")]
    [System.SerializableAttribute()]
    public partial class RetornoSistema : GIR.Integracao.ServicoGASC.Retorno {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoGASC.SistemaUsuario SistemaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoGASC.SistemaUsuario Sistema {
            get {
                return this.SistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemaField, value) != true)) {
                    this.SistemaField = value;
                    this.RaisePropertyChanged("Sistema");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoUsuario", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Retornos")]
    [System.SerializableAttribute()]
    public partial class RetornoUsuario : GIR.Integracao.ServicoGASC.Retorno {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoGASC.Usuario UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoGASC.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Models")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoGASC.DadoComplementarUsuario[] DadosComplementaresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEspecializacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoGASC.PerfilUsuario[] PerfisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoGASC.TipoUsuario TipoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoGASC.DadoComplementarUsuario[] DadosComplementares {
            get {
                return this.DadosComplementaresField;
            }
            set {
                if ((object.ReferenceEquals(this.DadosComplementaresField, value) != true)) {
                    this.DadosComplementaresField = value;
                    this.RaisePropertyChanged("DadosComplementares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEspecializacao {
            get {
                return this.IdEspecializacaoField;
            }
            set {
                if ((this.IdEspecializacaoField.Equals(value) != true)) {
                    this.IdEspecializacaoField = value;
                    this.RaisePropertyChanged("IdEspecializacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoGASC.PerfilUsuario[] Perfis {
            get {
                return this.PerfisField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfisField, value) != true)) {
                    this.PerfisField = value;
                    this.RaisePropertyChanged("Perfis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoGASC.TipoUsuario TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilUsuario", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Models")]
    [System.SerializableAttribute()]
    public partial class PerfilUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoGASC.FuncionalidadeUsuario[] FuncionalidadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoGASC.FuncionalidadeUsuario[] Funcionalidades {
            get {
                return this.FuncionalidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionalidadesField, value) != true)) {
                    this.FuncionalidadesField = value;
                    this.RaisePropertyChanged("Funcionalidades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuncionalidadeUsuario", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Models")]
    [System.SerializableAttribute()]
    public partial class FuncionalidadeUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiglaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoGASC.SistemaUsuario SistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SituacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sigla {
            get {
                return this.SiglaField;
            }
            set {
                if ((object.ReferenceEquals(this.SiglaField, value) != true)) {
                    this.SiglaField = value;
                    this.RaisePropertyChanged("Sigla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoGASC.SistemaUsuario Sistema {
            get {
                return this.SistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemaField, value) != true)) {
                    this.SistemaField = value;
                    this.RaisePropertyChanged("Sistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((this.SituacaoField.Equals(value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SistemaUsuario", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Models")]
    [System.SerializableAttribute()]
    public partial class SistemaUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiglaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SituacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sigla {
            get {
                return this.SiglaField;
            }
            set {
                if ((object.ReferenceEquals(this.SiglaField, value) != true)) {
                    this.SiglaField = value;
                    this.RaisePropertyChanged("Sigla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((this.SituacaoField.Equals(value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadoComplementarUsuario", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Models")]
    [System.SerializableAttribute()]
    public partial class DadoComplementarUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Chave {
            get {
                return this.ChaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveField, value) != true)) {
                    this.ChaveField = value;
                    this.RaisePropertyChanged("Chave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUsuario", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Models")]
    [System.SerializableAttribute()]
    public partial class TipoUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Erros")]
    [System.SerializableAttribute()]
    public partial class ServicoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoSistemas", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Retornos")]
    [System.SerializableAttribute()]
    public partial class RetornoSistemas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GIR.Integracao.ServicoGASC.SistemaUsuario[] SistemasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIR.Integracao.ServicoGASC.SistemaUsuario[] Sistemas {
            get {
                return this.SistemasField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemasField, value) != true)) {
                    this.SistemasField = value;
                    this.RaisePropertyChanged("Sistemas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoGASC.IServicoGASC")]
    public interface IServicoGASC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGASC/ObterUsuario", ReplyAction="http://tempuri.org/IServicoGASC/ObterUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoGASC.ServicoException), Action="http://tempuri.org/IServicoGASC/ObterUsuarioServicoExceptionFault", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Erros")]
        GIR.Integracao.ServicoGASC.RetornoUsuario ObterUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGASC/ListarPerfisUsuario", ReplyAction="http://tempuri.org/IServicoGASC/ListarPerfisUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoGASC.ServicoException), Action="http://tempuri.org/IServicoGASC/ListarPerfisUsuarioServicoExceptionFault", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Erros")]
        GIR.Integracao.ServicoGASC.RetornoPerfisUsuario ListarPerfisUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGASC/ListarDadosComplementaresUsuario", ReplyAction="http://tempuri.org/IServicoGASC/ListarDadosComplementaresUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoGASC.ServicoException), Action="http://tempuri.org/IServicoGASC/ListarDadosComplementaresUsuarioServicoExceptionF" +
            "ault", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Erros")]
        GIR.Integracao.ServicoGASC.RetornoDadosComplementaresUsuario ListarDadosComplementaresUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGASC/ListarUsuariosPerfil", ReplyAction="http://tempuri.org/IServicoGASC/ListarUsuariosPerfilResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoGASC.ServicoException), Action="http://tempuri.org/IServicoGASC/ListarUsuariosPerfilServicoExceptionFault", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Erros")]
        GIR.Integracao.ServicoGASC.RetornoUsuarios ListarUsuariosPerfil(string perfilUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGASC/ListarUsuariosPerfilSistema", ReplyAction="http://tempuri.org/IServicoGASC/ListarUsuariosPerfilSistemaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoGASC.ServicoException), Action="http://tempuri.org/IServicoGASC/ListarUsuariosPerfilSistemaServicoExceptionFault", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Erros")]
        GIR.Integracao.ServicoGASC.RetornoUsuarios ListarUsuariosPerfilSistema(string perfilUsuario, string sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGASC/ListarSistemas", ReplyAction="http://tempuri.org/IServicoGASC/ListarSistemasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoGASC.ServicoException), Action="http://tempuri.org/IServicoGASC/ListarSistemasServicoExceptionFault", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Erros")]
        GIR.Integracao.ServicoGASC.RetornoSistemas ListarSistemas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGASC/ObterSistemaPorId", ReplyAction="http://tempuri.org/IServicoGASC/ObterSistemaPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoGASC.ServicoException), Action="http://tempuri.org/IServicoGASC/ObterSistemaPorIdServicoExceptionFault", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Erros")]
        GIR.Integracao.ServicoGASC.RetornoSistema ObterSistemaPorId(int idSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGASC/ObterSistemaPorSigla", ReplyAction="http://tempuri.org/IServicoGASC/ObterSistemaPorSiglaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoGASC.ServicoException), Action="http://tempuri.org/IServicoGASC/ObterSistemaPorSiglaServicoExceptionFault", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Erros")]
        GIR.Integracao.ServicoGASC.RetornoSistema ObterSistemaPorSigla(string siglaSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGASC/AutenticarUsuario", ReplyAction="http://tempuri.org/IServicoGASC/AutenticarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIR.Integracao.ServicoGASC.ServicoException), Action="http://tempuri.org/IServicoGASC/AutenticarUsuarioServicoExceptionFault", Name="ServicoException", Namespace="http://schemas.datacontract.org/2004/07/GASC.Servico.Erros")]
        GIR.Integracao.ServicoGASC.RetornoUsuario AutenticarUsuario(string login, string senha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoGASCChannel : GIR.Integracao.ServicoGASC.IServicoGASC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoGASCClient : System.ServiceModel.ClientBase<GIR.Integracao.ServicoGASC.IServicoGASC>, GIR.Integracao.ServicoGASC.IServicoGASC {
        
        public ServicoGASCClient() {
        }
        
        public ServicoGASCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoGASCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoGASCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoGASCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GIR.Integracao.ServicoGASC.RetornoUsuario ObterUsuario(int idUsuario) {
            return base.Channel.ObterUsuario(idUsuario);
        }
        
        public GIR.Integracao.ServicoGASC.RetornoPerfisUsuario ListarPerfisUsuario(int idUsuario) {
            return base.Channel.ListarPerfisUsuario(idUsuario);
        }
        
        public GIR.Integracao.ServicoGASC.RetornoDadosComplementaresUsuario ListarDadosComplementaresUsuario(int idUsuario) {
            return base.Channel.ListarDadosComplementaresUsuario(idUsuario);
        }
        
        public GIR.Integracao.ServicoGASC.RetornoUsuarios ListarUsuariosPerfil(string perfilUsuario) {
            return base.Channel.ListarUsuariosPerfil(perfilUsuario);
        }
        
        public GIR.Integracao.ServicoGASC.RetornoUsuarios ListarUsuariosPerfilSistema(string perfilUsuario, string sistema) {
            return base.Channel.ListarUsuariosPerfilSistema(perfilUsuario, sistema);
        }
        
        public GIR.Integracao.ServicoGASC.RetornoSistemas ListarSistemas() {
            return base.Channel.ListarSistemas();
        }
        
        public GIR.Integracao.ServicoGASC.RetornoSistema ObterSistemaPorId(int idSistema) {
            return base.Channel.ObterSistemaPorId(idSistema);
        }
        
        public GIR.Integracao.ServicoGASC.RetornoSistema ObterSistemaPorSigla(string siglaSistema) {
            return base.Channel.ObterSistemaPorSigla(siglaSistema);
        }
        
        public GIR.Integracao.ServicoGASC.RetornoUsuario AutenticarUsuario(string login, string senha) {
            return base.Channel.AutenticarUsuario(login, senha);
        }
    }
}
