//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIR.Core.Negocio.Mensagem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GIR.Core.Negocio.Mensagem.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo {0} é obrigatório!.
        /// </summary>
        public static string MA001 {
            get {
                return ResourceManager.GetString("MA001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Data Inicial não pode ser maior que a Data Final.
        /// </summary>
        public static string MA003 {
            get {
                return ResourceManager.GetString("MA003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo informado é inválido..
        /// </summary>
        public static string MA004 {
            get {
                return ResourceManager.GetString("MA004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os arquivos de Informe de rendimentos serão disponibilizados para consulta aos usuários. Essa ação não poderá ser desfeita! Confirma o processamento? (S/N).
        /// </summary>
        public static string MA005 {
            get {
                return ResourceManager.GetString("MA005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar os registros desta rotina..
        /// </summary>
        public static string MH005 {
            get {
                return ResourceManager.GetString("MH005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferir os registros para disponibilização web..
        /// </summary>
        public static string MH006 {
            get {
                return ResourceManager.GetString("MH006", resourceCulture);
            }
        }
    }
}
